// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (tenant_id, name, sort_order, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, sort_order, is_active
`

type CreateCategoryParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.TenantID,
		arg.Name,
		arg.SortOrder,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1 AND tenant_id = $2
`

type DeleteCategoryParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.TenantID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, tenant_id, name, sort_order, is_active
FROM categories
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetCategoryByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.ID, arg.TenantID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const listCategoriesByTenant = `-- name: ListCategoriesByTenant :many
SELECT id, tenant_id, name, sort_order, is_active
FROM categories
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListCategoriesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $3, sort_order = $4, is_active = $5
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, sort_order, is_active
`

type UpdateCategoryParams struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.SortOrder,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}
