// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (tenant_id, category_id, name, description, price, image_url, tags, is_available, is_sold_out)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, category_id, name, description, price, image_url, tags, is_available, is_sold_out, created_at
`

type CreateMenuItemParams struct {
	TenantID    pgtype.UUID    `json:"tenant_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	ImageUrl    string         `json:"image_url"`
	Tags        []string       `json:"tags"`
	IsAvailable bool           `json:"is_available"`
	IsSoldOut   bool           `json:"is_sold_out"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImageUrl,
		arg.Tags,
		arg.IsAvailable,
		arg.IsSoldOut,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.Tags,
		&i.IsAvailable,
		&i.IsSoldOut,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items
WHERE id = $1 AND tenant_id = $2
`

type DeleteMenuItemParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, arg.ID, arg.TenantID)
	return err
}

const getMenuItemByID = `-- name: GetMenuItemByID :one
SELECT id, tenant_id, category_id, name, description, price, image_url, tags, is_available, is_sold_out, created_at
FROM menu_items
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetMenuItemByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetMenuItemByID(ctx context.Context, arg GetMenuItemByIDParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItemByID, arg.ID, arg.TenantID)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.Tags,
		&i.IsAvailable,
		&i.IsSoldOut,
		&i.CreatedAt,
	)
	return i, err
}

const listMenuItemsByCategory = `-- name: ListMenuItemsByCategory :many
SELECT id, tenant_id, category_id, name, description, price, image_url, tags, is_available, is_sold_out, created_at
FROM menu_items
WHERE tenant_id = $1 AND category_id = $2 AND is_available = TRUE
ORDER BY name ASC
`

type ListMenuItemsByCategoryParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) ListMenuItemsByCategory(ctx context.Context, arg ListMenuItemsByCategoryParams) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByCategory, arg.TenantID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.Tags,
			&i.IsAvailable,
			&i.IsSoldOut,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsByTenant = `-- name: ListMenuItemsByTenant :many
SELECT id, tenant_id, category_id, name, description, price, image_url, tags, is_available, is_sold_out, created_at
FROM menu_items
WHERE tenant_id = $1 AND is_available = TRUE
ORDER BY name ASC
`

func (q *Queries) ListMenuItemsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.ImageUrl,
			&i.Tags,
			&i.IsAvailable,
			&i.IsSoldOut,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleMenuItemSoldOut = `-- name: ToggleMenuItemSoldOut :one
UPDATE menu_items
SET is_sold_out = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, is_sold_out
`

type ToggleMenuItemSoldOutParams struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	IsSoldOut bool        `json:"is_sold_out"`
}

type ToggleMenuItemSoldOutRow struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Name      string      `json:"name"`
	IsSoldOut bool        `json:"is_sold_out"`
}

func (q *Queries) ToggleMenuItemSoldOut(ctx context.Context, arg ToggleMenuItemSoldOutParams) (ToggleMenuItemSoldOutRow, error) {
	row := q.db.QueryRow(ctx, toggleMenuItemSoldOut, arg.ID, arg.TenantID, arg.IsSoldOut)
	var i ToggleMenuItemSoldOutRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.IsSoldOut,
	)
	return i, err
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET category_id = $3, name = $4, description = $5, price = $6, image_url = $7, tags = $8, is_available = $9
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, category_id, name, description, price, image_url, tags, is_available, is_sold_out, created_at
`

type UpdateMenuItemParams struct {
	ID          pgtype.UUID    `json:"id"`
	TenantID    pgtype.UUID    `json:"tenant_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	ImageUrl    string         `json:"image_url"`
	Tags        []string       `json:"tags"`
	IsAvailable bool           `json:"is_available"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.ImageUrl,
		arg.Tags,
		arg.IsAvailable,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.ImageUrl,
		&i.Tags,
		&i.IsAvailable,
		&i.IsSoldOut,
		&i.CreatedAt,
	)
	return i, err
}
