// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OrderStatus string

const (
	OrderStatusPendingGrace OrderStatus = "pending_grace"
	OrderStatusNotStarted   OrderStatus = "not_started"
	OrderStatusPreparing    OrderStatus = "preparing"
	OrderStatusReady        OrderStatus = "ready"
	OrderStatusDelivered    OrderStatus = "delivered"
	OrderStatusCancelled    OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentStatus string

const (
	PaymentStatusUnpaid   PaymentStatus = "unpaid"
	PaymentStatusPaid     PaymentStatus = "paid"
	PaymentStatusRefunded PaymentStatus = "refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PlanTier string

const (
	PlanTierStandard   PlanTier = "standard"
	PlanTierVip        PlanTier = "vip"
	PlanTierEnterprise PlanTier = "enterprise"
)

func (e *PlanTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanTier(s)
	case string:
		*e = PlanTier(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanTier: %T", src)
	}
	return nil
}

type NullPlanTier struct {
	PlanTier PlanTier `json:"plan_tier"`
	Valid    bool     `json:"valid"` // Valid is true if PlanTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanTier) Scan(value interface{}) error {
	if value == nil {
		ns.PlanTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanTier), nil
}

type UserRole string

const (
	UserRoleSuperAdmin UserRole = "super_admin"
	UserRoleOwner      UserRole = "owner"
	UserRoleManager    UserRole = "manager"
	UserRoleKitchen    UserRole = "kitchen"
	UserRoleWaiter     UserRole = "waiter"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Category struct {
	ID        pgtype.UUID `json:"id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Name      string      `json:"name"`
	SortOrder int32       `json:"sort_order"`
	IsActive  bool        `json:"is_active"`
}

type ItemModifierGroup struct {
	MenuItemID      pgtype.UUID `json:"menu_item_id"`
	ModifierGroupID pgtype.UUID `json:"modifier_group_id"`
}

type MenuItem struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	ImageUrl    string             `json:"image_url"`
	Tags        []string           `json:"tags"`
	IsAvailable bool               `json:"is_available"`
	IsSoldOut   bool               `json:"is_sold_out"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Modifier struct {
	ID              pgtype.UUID    `json:"id"`
	ModifierGroupID pgtype.UUID    `json:"modifier_group_id"`
	Name            string         `json:"name"`
	PriceAdjustment pgtype.Numeric `json:"price_adjustment"`
}

type ModifierGroup struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Name          string      `json:"name"`
	MinSelections int32       `json:"min_selections"`
	MaxSelections int32       `json:"max_selections"`
}

type Order struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	TableID              pgtype.UUID        `json:"table_id"`
	TableNumber          string             `json:"table_number"`
	CustomerSessionToken string             `json:"customer_session_token"`
	Status               OrderStatus        `json:"status"`
	PaymentStatus        PaymentStatus      `json:"payment_status"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	GracePeriodEndsAt    pgtype.Timestamptz `json:"grace_period_ends_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID         pgtype.UUID    `json:"id"`
	OrderID    pgtype.UUID    `json:"order_id"`
	MenuItemID pgtype.UUID    `json:"menu_item_id"`
	ItemName   string         `json:"item_name"`
	UnitPrice  pgtype.Numeric `json:"unit_price"`
	Quantity   int32          `json:"quantity"`
	Notes      pgtype.Text    `json:"notes"`
}

type OrderItemModifier struct {
	ID           pgtype.UUID    `json:"id"`
	OrderItemID  pgtype.UUID    `json:"order_item_id"`
	ModifierID   pgtype.UUID    `json:"modifier_id"`
	ModifierName string         `json:"modifier_name"`
	PriceApplied pgtype.Numeric `json:"price_applied"`
}

type RestaurantTable struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	TableNumber string      `json:"table_number"`
	QrSecret    string      `json:"qr_secret"`
	IsActive    bool        `json:"is_active"`
}

type Tenant struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Plan        PlanTier           `json:"plan"`
	Currency    string             `json:"currency"`
	ThemeConfig []byte             `json:"theme_config"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
