// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrderInGrace = `-- name: CancelOrderInGrace :one
UPDATE orders
SET status = 'cancelled', updated_at = NOW()
WHERE id = $1 
  AND tenant_id = $2 
  AND customer_session_token = $3 
  AND status = 'pending_grace' 
  AND grace_period_ends_at > NOW()
RETURNING id, tenant_id, status
`

type CancelOrderInGraceParams struct {
	ID                   pgtype.UUID `json:"id"`
	TenantID             pgtype.UUID `json:"tenant_id"`
	CustomerSessionToken string      `json:"customer_session_token"`
}

type CancelOrderInGraceRow struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   OrderStatus `json:"status"`
}

func (q *Queries) CancelOrderInGrace(ctx context.Context, arg CancelOrderInGraceParams) (CancelOrderInGraceRow, error) {
	row := q.db.QueryRow(ctx, cancelOrderInGrace, arg.ID, arg.TenantID, arg.CustomerSessionToken)
	var i CancelOrderInGraceRow
	err := row.Scan(&i.ID, &i.TenantID, &i.Status)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    tenant_id, table_id, table_number, customer_session_token,
    status, payment_status, total_amount, grace_period_ends_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, table_id, table_number, customer_session_token, status, payment_status, total_amount, grace_period_ends_at, created_at
`

type CreateOrderParams struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	TableID              pgtype.UUID        `json:"table_id"`
	TableNumber          string             `json:"table_number"`
	CustomerSessionToken string             `json:"customer_session_token"`
	Status               OrderStatus        `json:"status"`
	PaymentStatus        PaymentStatus      `json:"payment_status"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	GracePeriodEndsAt    pgtype.Timestamptz `json:"grace_period_ends_at"`
}

type CreateOrderRow struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	TableID              pgtype.UUID        `json:"table_id"`
	TableNumber          string             `json:"table_number"`
	CustomerSessionToken string             `json:"customer_session_token"`
	Status               OrderStatus        `json:"status"`
	PaymentStatus        PaymentStatus      `json:"payment_status"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	GracePeriodEndsAt    pgtype.Timestamptz `json:"grace_period_ends_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.TenantID,
		arg.TableID,
		arg.TableNumber,
		arg.CustomerSessionToken,
		arg.Status,
		arg.PaymentStatus,
		arg.TotalAmount,
		arg.GracePeriodEndsAt,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TableID,
		&i.TableNumber,
		&i.CustomerSessionToken,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.GracePeriodEndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, menu_item_id, item_name, unit_price, quantity, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, menu_item_id, item_name, unit_price, quantity, notes
`

type CreateOrderItemParams struct {
	OrderID    pgtype.UUID    `json:"order_id"`
	MenuItemID pgtype.UUID    `json:"menu_item_id"`
	ItemName   string         `json:"item_name"`
	UnitPrice  pgtype.Numeric `json:"unit_price"`
	Quantity   int32          `json:"quantity"`
	Notes      pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.ItemName,
		arg.UnitPrice,
		arg.Quantity,
		arg.Notes,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.ItemName,
		&i.UnitPrice,
		&i.Quantity,
		&i.Notes,
	)
	return i, err
}

const createOrderItemModifier = `-- name: CreateOrderItemModifier :one
INSERT INTO order_item_modifiers (order_item_id, modifier_id, modifier_name, price_applied)
VALUES ($1, $2, $3, $4)
RETURNING id, order_item_id, modifier_id, modifier_name, price_applied
`

type CreateOrderItemModifierParams struct {
	OrderItemID  pgtype.UUID    `json:"order_item_id"`
	ModifierID   pgtype.UUID    `json:"modifier_id"`
	ModifierName string         `json:"modifier_name"`
	PriceApplied pgtype.Numeric `json:"price_applied"`
}

func (q *Queries) CreateOrderItemModifier(ctx context.Context, arg CreateOrderItemModifierParams) (OrderItemModifier, error) {
	row := q.db.QueryRow(ctx, createOrderItemModifier,
		arg.OrderItemID,
		arg.ModifierID,
		arg.ModifierName,
		arg.PriceApplied,
	)
	var i OrderItemModifier
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.ModifierID,
		&i.ModifierName,
		&i.PriceApplied,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, tenant_id, table_id, table_number, customer_session_token, status, payment_status, total_amount, grace_period_ends_at, created_at
FROM orders
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetOrderByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

type GetOrderByIDRow struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	TableID              pgtype.UUID        `json:"table_id"`
	TableNumber          string             `json:"table_number"`
	CustomerSessionToken string             `json:"customer_session_token"`
	Status               OrderStatus        `json:"status"`
	PaymentStatus        PaymentStatus      `json:"payment_status"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	GracePeriodEndsAt    pgtype.Timestamptz `json:"grace_period_ends_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, arg.ID, arg.TenantID)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TableID,
		&i.TableNumber,
		&i.CustomerSessionToken,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.GracePeriodEndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveOrdersByTenant = `-- name: ListActiveOrdersByTenant :many
SELECT id, tenant_id, table_id, table_number, status, payment_status, total_amount, grace_period_ends_at, created_at
FROM orders
WHERE tenant_id = $1 AND status NOT IN ('delivered', 'cancelled')
ORDER BY created_at DESC
`

type ListActiveOrdersByTenantRow struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	TableID           pgtype.UUID        `json:"table_id"`
	TableNumber       string             `json:"table_number"`
	Status            OrderStatus        `json:"status"`
	PaymentStatus     PaymentStatus      `json:"payment_status"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	GracePeriodEndsAt pgtype.Timestamptz `json:"grace_period_ends_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActiveOrdersByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListActiveOrdersByTenantRow, error) {
	rows, err := q.db.Query(ctx, listActiveOrdersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOrdersByTenantRow{}
	for rows.Next() {
		var i ListActiveOrdersByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TableID,
			&i.TableNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.TotalAmount,
			&i.GracePeriodEndsAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemModifiersByItemID = `-- name: ListOrderItemModifiersByItemID :many
SELECT id, order_item_id, modifier_id, modifier_name, price_applied
FROM order_item_modifiers
WHERE order_item_id = $1
`

func (q *Queries) ListOrderItemModifiersByItemID(ctx context.Context, orderItemID pgtype.UUID) ([]OrderItemModifier, error) {
	rows, err := q.db.Query(ctx, listOrderItemModifiersByItemID, orderItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItemModifier{}
	for rows.Next() {
		var i OrderItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.OrderItemID,
			&i.ModifierID,
			&i.ModifierName,
			&i.PriceApplied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, menu_item_id, item_name, unit_price, quantity, notes
FROM order_items
WHERE order_id = $1
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.ItemName,
			&i.UnitPrice,
			&i.Quantity,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $3, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, status, updated_at
`

type UpdateOrderStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   OrderStatus `json:"status"`
}

type UpdateOrderStatusRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Status    OrderStatus        `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (UpdateOrderStatusRow, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.TenantID, arg.Status)
	var i UpdateOrderStatusRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
const bulkCancelTableOrders = `-- name: BulkCancelTableOrders :exec
UPDATE orders
SET status = 'cancelled', updated_at = NOW()
WHERE tenant_id = $1
  AND table_number = $2
  AND status NOT IN ('delivered', 'cancelled')
`

type BulkCancelTableOrdersParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	TableNumber string      `json:"table_number"`
}

func (q *Queries) BulkCancelTableOrders(ctx context.Context, arg BulkCancelTableOrdersParams) error {
	_, err := q.db.Exec(ctx, bulkCancelTableOrders, arg.TenantID, arg.TableNumber)
	return err
}

const bulkCancelAllActiveOrders = `-- name: BulkCancelAllActiveOrders :exec
UPDATE orders
SET status = 'cancelled', updated_at = NOW()
WHERE tenant_id = $1
  AND status NOT IN ('delivered', 'cancelled')
`

func (q *Queries) BulkCancelAllActiveOrders(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bulkCancelAllActiveOrders, tenantID)
	return err
}
