// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelOrderInGrace(ctx context.Context, arg CancelOrderInGraceParams) (CancelOrderInGraceRow, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOrderItemModifier(ctx context.Context, arg CreateOrderItemModifierParams) (OrderItemModifier, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (RestaurantTable, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) error
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetMenuItemByID(ctx context.Context, arg GetMenuItemByIDParams) (MenuItem, error)
	GetModifierByID(ctx context.Context, arg GetModifierByIDParams) (GetModifierByIDRow, error)
	GetModifierByIDAndMenuItemID(ctx context.Context, arg GetModifierByIDAndMenuItemIDParams) (GetModifierByIDAndMenuItemIDRow, error)
	GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (GetOrderByIDRow, error)
	GetTableByNumber(ctx context.Context, arg GetTableByNumberParams) (RestaurantTable, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListActiveOrdersByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListActiveOrdersByTenantRow, error)
	ListActiveTenants(ctx context.Context) ([]Tenant, error)
	ListCategoriesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Category, error)
	ListMenuItemsByCategory(ctx context.Context, arg ListMenuItemsByCategoryParams) ([]MenuItem, error)
	ListMenuItemsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]MenuItem, error)
	ListOrderItemModifiersByItemID(ctx context.Context, orderItemID pgtype.UUID) ([]OrderItemModifier, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error)
	ListTablesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]RestaurantTable, error)
	ToggleMenuItemSoldOut(ctx context.Context, arg ToggleMenuItemSoldOutParams) (ToggleMenuItemSoldOutRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (UpdateOrderStatusRow, error)
	UpdateTableQRSecret(ctx context.Context, arg UpdateTableQRSecretParams) (UpdateTableQRSecretRow, error)
	UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) (Tenant, error)
	UpdateTenantTheme(ctx context.Context, arg UpdateTenantThemeParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
