// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tables.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTable = `-- name: CreateTable :one
INSERT INTO restaurant_tables (tenant_id, table_number, qr_secret, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, table_number, qr_secret, is_active
`

type CreateTableParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	TableNumber string      `json:"table_number"`
	QrSecret    string      `json:"qr_secret"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (RestaurantTable, error) {
	row := q.db.QueryRow(ctx, createTable,
		arg.TenantID,
		arg.TableNumber,
		arg.QrSecret,
		arg.IsActive,
	)
	var i RestaurantTable
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TableNumber,
		&i.QrSecret,
		&i.IsActive,
	)
	return i, err
}

const getTableByNumber = `-- name: GetTableByNumber :one
SELECT id, tenant_id, table_number, qr_secret, is_active
FROM restaurant_tables
WHERE tenant_id = $1 AND table_number = $2 AND is_active = TRUE
LIMIT 1
`

type GetTableByNumberParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	TableNumber string      `json:"table_number"`
}

func (q *Queries) GetTableByNumber(ctx context.Context, arg GetTableByNumberParams) (RestaurantTable, error) {
	row := q.db.QueryRow(ctx, getTableByNumber, arg.TenantID, arg.TableNumber)
	var i RestaurantTable
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TableNumber,
		&i.QrSecret,
		&i.IsActive,
	)
	return i, err
}

const listTablesByTenant = `-- name: ListTablesByTenant :many
SELECT id, tenant_id, table_number, qr_secret, is_active
FROM restaurant_tables
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY table_number ASC
`

func (q *Queries) ListTablesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]RestaurantTable, error) {
	rows, err := q.db.Query(ctx, listTablesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RestaurantTable{}
	for rows.Next() {
		var i RestaurantTable
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TableNumber,
			&i.QrSecret,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTableQRSecret = `-- name: UpdateTableQRSecret :one
UPDATE restaurant_tables
SET qr_secret = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, table_number, qr_secret
`

type UpdateTableQRSecretParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	QrSecret string      `json:"qr_secret"`
}

type UpdateTableQRSecretRow struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	TableNumber string      `json:"table_number"`
	QrSecret    string      `json:"qr_secret"`
}

func (q *Queries) UpdateTableQRSecret(ctx context.Context, arg UpdateTableQRSecretParams) (UpdateTableQRSecretRow, error) {
	row := q.db.QueryRow(ctx, updateTableQRSecret, arg.ID, arg.TenantID, arg.QrSecret)
	var i UpdateTableQRSecretRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TableNumber,
		&i.QrSecret,
	)
	return i, err
}
