// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (slug, name, plan, currency, theme_config)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, plan, currency, theme_config, is_active, created_at, updated_at
`

type CreateTenantParams struct {
	Slug        string   `json:"slug"`
	Name        string   `json:"name"`
	Plan        PlanTier `json:"plan"`
	Currency    string   `json:"currency"`
	ThemeConfig []byte   `json:"theme_config"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Slug,
		arg.Name,
		arg.Plan,
		arg.Currency,
		arg.ThemeConfig,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Plan,
		&i.Currency,
		&i.ThemeConfig,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, name, plan, currency, theme_config, is_active, created_at, updated_at
FROM tenants
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Plan,
		&i.Currency,
		&i.ThemeConfig,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, plan, currency, theme_config, is_active, created_at, updated_at
FROM tenants
WHERE slug = $1 AND is_active = TRUE
LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Plan,
		&i.Currency,
		&i.ThemeConfig,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTenants = `-- name: ListActiveTenants :many
SELECT id, slug, name, plan, currency, theme_config, is_active, created_at, updated_at
FROM tenants
WHERE is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActiveTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listActiveTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Plan,
			&i.Currency,
			&i.ThemeConfig,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantPlan = `-- name: UpdateTenantPlan :one
UPDATE tenants
SET plan = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, name, plan, currency, theme_config, is_active, created_at, updated_at
`

type UpdateTenantPlanParams struct {
	ID   pgtype.UUID `json:"id"`
	Plan PlanTier    `json:"plan"`
}

func (q *Queries) UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantPlan, arg.ID, arg.Plan)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Plan,
		&i.Currency,
		&i.ThemeConfig,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantTheme = `-- name: UpdateTenantTheme :one
UPDATE tenants
SET theme_config = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, slug, name, plan, currency, theme_config, is_active, created_at, updated_at
`

type UpdateTenantThemeParams struct {
	ID          pgtype.UUID `json:"id"`
	ThemeConfig []byte      `json:"theme_config"`
}

func (q *Queries) UpdateTenantTheme(ctx context.Context, arg UpdateTenantThemeParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantTheme, arg.ID, arg.ThemeConfig)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Plan,
		&i.Currency,
		&i.ThemeConfig,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
